# Generated by Django 5.1.1 on 2024-09-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_homeowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='homeowner',
        ),
    ]
