# Generated by Django 5.1.1 on 2024-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_homeowner_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
