# Generated by Django 5.1.1 on 2024-09-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_data',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
