# Generated by Django 5.1.1 on 2024-09-19 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_cart_data_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_data',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
